include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Lints recommended by the Flutter team.
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides

analyzer:
  plugins:
    - custom_lint
